"""Edit excursion model

Revision ID: 0ddc094ff425
Revises: 7afde325a5a2
Create Date: 2025-07-10 14:02:50.571122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddc094ff425'
down_revision: Union[str, None] = '7afde325a5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursion_materials', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursion_materials', 'text')
    # ### end Alembic commands ###
