"""update faq

Revision ID: 4d0e070965e5
Revises: 0db44cd7ab10
Create Date: 2025-07-14 11:21:33.246587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0e070965e5'
down_revision: Union[str, None] = '0db44cd7ab10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['faq.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_keywords')
    # ### end Alembic commands ###
