"""Add ON DELETE CASCADE

Revision ID: 744d273f0b19
Revises: a7cd2f6bf2a6
Create Date: 2025-07-28 02:40:11.423801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744d273f0b19'
down_revision: Union[str, None] = 'a7cd2f6bf2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback_attachments', 'feedback_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('feedback_attachments_feedback_id_fkey'), 'feedback_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_attachments', 'feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_attachments_feedback_id_fkey'), 'feedback_attachments', 'feedback', ['feedback_id'], ['id'])
    op.alter_column('feedback_attachments', 'feedback_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
