"""Add excursion and materials tables

Revision ID: 7afde325a5a2
Revises: ce4b5ca16ae1
Create Date: 2025-07-10 13:51:06.143082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afde325a5a2'
down_revision: Union[str, None] = 'ce4b5ca16ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_excursions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excursion_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['excursion_id'], ['virtual_excursions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excursion_materials')
    op.drop_table('virtual_excursions')
    # ### end Alembic commands ###
