"""Update ExcursionMaterial model

Revision ID: 87e3128da0fb
Revises: 0ddc094ff425
Create Date: 2025-07-12 22:25:29.750431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e3128da0fb'
down_revision: Union[str, None] = '0ddc094ff425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursion_materials', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('excursion_materials', 'telegram_file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('excursion_materials', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursion_materials', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('excursion_materials', 'telegram_file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('excursion_materials', 'name')
    # ### end Alembic commands ###
