"""fix feedback

Revision ID: a7cd2f6bf2a6
Revises: 55723bb86b1a
Create Date: 2025-07-27 20:42:04.215127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cd2f6bf2a6'
down_revision: Union[str, None] = '55723bb86b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feedback', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('feedback', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('feedback', 'is_anonymous')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('feedback', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('feedback', 'is_read')
    op.drop_table('feedback_attachments')
    # ### end Alembic commands ###
