"""добавила поле в canteen_menu

Revision ID: b165bb786989
Revises: c7d57053f029
Create Date: 2025-07-16 17:15:24.240601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b165bb786989'
down_revision: Union[str, None] = 'c7d57053f029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteen_menu', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canteen_menu', 'file_type')
    # ### end Alembic commands ###
