"""2.0

Revision ID: ce4b5ca16ae1
Revises: 928b5e68768a
Create Date: 2025-07-08 13:26:41.559558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce4b5ca16ae1'
down_revision: Union[str, None] = '928b5e68768a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canteen_info')
    op.drop_column('company_info', 'created_at')
    op.drop_column('feedback', 'created_at')
    op.drop_column('registration_requests', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_requests', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('company_info', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('canteen_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_schedule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('menu_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('canteen_info_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('canteen_info_pkey'))
    )
    # ### end Alembic commands ###
